/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Conexion;
import Modelo.Usuario;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class FrmRegistro extends javax.swing.JFrame {
    private Conexion conect;
    /**
     * Creates new form FrmInicioSesion
     */
    public FrmRegistro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void cerrarConexion(){ //Función para cerrar la conexión con la base de datos
        if (conect != null) {
            try {
                conect.Conexion().close();
            } catch ( SQLException e ) { 
                System.out.println( e.getMessage());
            }
        }
    }
    
    private boolean validarPassword(String pass){ //Función para validar que una contraseña sea de al menos 8 digitos
        if(pass.length()<7)
            return false;
        return true;
    }
    
    private boolean verificarPasswords(String pass1, String pass2){ //Función para verificar que dos contraseñas sean iguales
        if(pass1.compareTo(pass2)==0)
            return true;
        return false;
    }
    
    private boolean datosCompletos(){ //Función para validar que los campos de un formulario esten llenos
        if(!txtNombre.getText().isEmpty() && !txtApaterno.getText().isEmpty() && !txtAmaterno.getText().isEmpty() && !txtNick.getText().isEmpty() && !txtEmail.getText().isEmpty() && !txtPassword.getText().isEmpty() && !txtCfrmPass.getText().isEmpty())
            return true;
        return false;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblApaterno = new javax.swing.JLabel();
        txtApaterno = new javax.swing.JTextField();
        lblAmaterno = new javax.swing.JLabel();
        txtAmaterno = new javax.swing.JTextField();
        lblLogoReg = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblNick = new javax.swing.JLabel();
        txtNick = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblCfrmPass = new javax.swing.JLabel();
        txtCfrmPass = new javax.swing.JPasswordField();
        lblIcono = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblApaterno.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblApaterno.setForeground(new java.awt.Color(0, 0, 153));
        lblApaterno.setText("Apellido Paterno: ");
        getContentPane().add(lblApaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 160, 30));

        txtApaterno.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtApaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApaternoActionPerformed(evt);
            }
        });
        txtApaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApaternoKeyTyped(evt);
            }
        });
        getContentPane().add(txtApaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 580, 40));

        lblAmaterno.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblAmaterno.setForeground(new java.awt.Color(0, 0, 153));
        lblAmaterno.setText("Apellido Paterno: ");
        getContentPane().add(lblAmaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 160, 30));

        txtAmaterno.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtAmaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmaternoActionPerformed(evt);
            }
        });
        txtAmaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmaternoKeyTyped(evt);
            }
        });
        getContentPane().add(txtAmaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 580, 40));

        lblLogoReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoReg.png"))); // NOI18N
        getContentPane().add(lblLogoReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 200, 150));

        btnRegistrar.setBackground(new java.awt.Color(51, 0, 204));
        btnRegistrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrarse");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setOpaque(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 710, 290, 40));

        btnCancelar.setBackground(new java.awt.Color(255, 153, 0));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setOpaque(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 710, 270, 40));

        lblNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 153));
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 80, 30));

        txtNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 580, 40));

        txtEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 580, 40));

        lblNick.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblNick.setForeground(new java.awt.Color(0, 0, 153));
        lblNick.setText("Nickname:");
        getContentPane().add(lblNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 100, 30));

        txtNick.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNickActionPerformed(evt);
            }
        });
        txtNick.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNickFocusLost(evt);
            }
        });
        getContentPane().add(txtNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 580, 40));

        lblEmail.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 153));
        lblEmail.setText("Correo electronico:");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 190, 30));

        lblPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 0, 153));
        lblPassword.setText("Contraseña:");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 190, 30));

        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 580, 40));

        lblCfrmPass.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblCfrmPass.setForeground(new java.awt.Color(0, 0, 153));
        lblCfrmPass.setText("Confirmar contraseña:");
        getContentPane().add(lblCfrmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, 200, 30));

        txtCfrmPass.setEnabled(false);
        txtCfrmPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCfrmPassFocusLost(evt);
            }
        });
        getContentPane().add(txtCfrmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, 580, 40));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoApp.png"))); // NOI18N
        getContentPane().add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 100));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 769));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            JOptionPane.showMessageDialog(this,"No se pueden ingresar digitos en este campo","Error de tipos",JOptionPane.INFORMATION_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNickActionPerformed

    private void txtNickFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNickFocusLost
        // TODO add your handling code here:
        conect = new Conexion();
        if(conect.buscarUsuario(txtNick.getText()))
            txtNick.setText(null);

        cerrarConexion();
    }//GEN-LAST:event_txtNickFocusLost

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        // TODO add your handling code here:
        if(!validarPassword(txtPassword.getText())){
            JOptionPane.showMessageDialog(null,"La contraseña debe tener al menos 8 caracteres o digitos","Contraseña insegura",JOptionPane.ERROR_MESSAGE);
            txtPassword.setText(null);
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        if(!txtPassword.getText().isEmpty() && validarPassword(txtPassword.getText()))
        txtCfrmPass.setEnabled(true);
        else
        txtCfrmPass.setEnabled(false);
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtCfrmPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCfrmPassFocusLost
        // TODO add your handling code here:
        if(!verificarPasswords(txtPassword.getText(),txtCfrmPass.getText())){
            JOptionPane.showMessageDialog(null,"Ingrese nuevamente las contraseñas","Las contraseñas no coinciden",JOptionPane.ERROR_MESSAGE);
            txtCfrmPass.setText(null);
        }
    }//GEN-LAST:event_txtCfrmPassFocusLost

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        if(datosCompletos()){
            Usuario nvo = new Usuario();
            nvo.setNombre(txtNombre.getText());
            nvo.setNickname(txtNick.getText());
            nvo.setPassword(txtPassword.getText());
            nvo.setEmail(txtEmail.getText());
            nvo.setaMaterno(txtAmaterno.getText());
            nvo.setaPaterno(txtApaterno.getText());
            conect = new Conexion();
            if(!conect.agregar(nvo))
                JOptionPane.showMessageDialog(null,"Hubo un problema al agregar al usuario","Error al agregar",JOptionPane.ERROR_MESSAGE);
            else{
                FrmUsuario frmU = new FrmUsuario(txtNick.getText());
                frmU.setVisible(true);
                dispose();
            }   
            cerrarConexion();
        }else{
            JOptionPane.showMessageDialog(null,"Debes llenar primero todos los campos","Datos incompletos",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFocusLost

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Realmente deseas cancelar el registro?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)==0){
            FrmInicioS frmIs = new FrmInicioS();
            frmIs.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void txtApaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApaternoActionPerformed

    private void txtApaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApaternoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            JOptionPane.showMessageDialog(this,"No se pueden ingresar digitos en este campo","Error de tipos",JOptionPane.INFORMATION_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtApaternoKeyTyped

    private void txtAmaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmaternoActionPerformed

    private void txtAmaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmaternoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            JOptionPane.showMessageDialog(this,"No se pueden ingresar digitos en este campo","Error de tipos",JOptionPane.INFORMATION_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtAmaternoKeyTyped

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistro().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblAmaterno;
    private javax.swing.JLabel lblApaterno;
    private javax.swing.JLabel lblCfrmPass;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblLogoReg;
    private javax.swing.JLabel lblNick;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtAmaterno;
    private javax.swing.JTextField txtApaterno;
    private javax.swing.JPasswordField txtCfrmPass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNick;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
